export const dougisms = [
  "No, of course not.",
  "Fuck no.",
  "Ummm... No.",
  "I liked it better before.",
  "That's bullshit.",
  "I don't give a shit.",
  "I am losing the ability to tell when you guys are joking on this stuff.",
  "Fuck it.",
  "Sigh.",
  "It's for hipsters.",
  "No, you're wrong.",
  "That looks awful.",
  "Yeah, if you're a moron.",
  "Oh, I thought I was speaking to adults...",
  "If it's new, you like it. God damn hipster.",
  "It's ruined.",
  "That's unusable.",
  "Only a child would like that.",
  "That really sounds like something I don't give a shit about.",
  "No.",
  "It's good if you like things that suck.",
  "I'm having an internal debate with myself as to whether to accept this constraint as a given or melt down in a fire of ridiculousness.",
  "Nine levels of my brain just seg-faulted at once.",
  "Fuck me with a chainsaw.",
  "I just want something usable."
]
